version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - mihaivarga
  assignees:
  - mihaivarga
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@firebase/firestore"
    versions:
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.1.6
    - 2.1.7
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
    - 2.2.4
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: "@firebase/util"
    versions:
    - 0.3.4
    - 0.4.0
    - 0.4.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: stylelint
    versions:
    - 13.9.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: semantic-release
    versions:
    - 17.2.3
  - dependency-name: karma-jasmine
    versions:
    - 4.0.1
  - dependency-name: inquirer-autocomplete-prompt
    versions:
    - 1.3.0
