name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@weblauncher'
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          npx lerna run build
      - name: Publish
        run: |
          git config --global user.email "me_shuv@yahoo.com"
          git config --global user.name "mihaivarga"
          npm config set access public
          npx lerna publish --contents dist --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Build demo
        run: |
          npm run build:prod
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
